name: CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: prefix-dev/setup-pixi@v0.8.1
      - run: |
          git config --global user.email "testbot@example.com"
          git config --global user.name "Testbot"
      - run: pixi run test
